export const teamsFixture = [
    {
        "id":"TEAM1",
        "name":"Marketing",
        "users":[
            "USR1",
            "USR3"
        ]
    },
    {
        "id":"TEAM2",
        "name":"Product & Engineering",
        "users":[
            "USR2",
            "USR3",
            "USR7",
            "USR8",
            "USR9"
        ]
    },
    {
        "id":"TEAM3",
        "name":"Finance",
        "users":[
            "USR4",
            "USR5"
        ]
    },
    {
        "id":"TEAM4",
        "name":"Sales",
        "users":[
            "USR10",
            "USR11",
            "USR12",
            "USR13"
        ]
    },
    {
        "id":"TEAM5",
        "name":"Operations",
        "users":[
            "USR6",
            "USR14"
        ]
    }
];