export const usersFixture = [
    {
        "id":"USR1",
        "first_name":"Eugene",
        "last_name":"Tran",
        "email":"eugene.tran@spendesk.com"
    },
    {
        "id":"USR2",
        "first_name":"Ralph",
        "last_name":"Romero",
        "email":"ralph.romero@spendesk.com"
    },
    {
        "id":"USR3",
        "first_name":"Tiffany",
        "last_name":"Frazier",
        "email":"tiffany.frazier@spendesk.com"
    },
    {
        "id":"USR4",
        "first_name":"Sandra",
        "last_name":"Reed",
        "email":"sandra.reed@spendesk.com"
    },
    {
        "id":"USR5",
        "first_name":"Jason",
        "last_name":"Casey",
        "email":"jason.casey@spendesk.com"
    }
]